name: dartlib
description: A Dart library for 1) implementing the server-side communication and ProntoGUI model and for 2) connecting Dart programs to the ProntoGUI App.
version: 0.0.60
publish_to: none    # Added this temporarily to deal with issue in dependency for statemachine, from a local path.
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  cbor: ^6.1.1
  protobuf: '>=2.0.0 <4.0.0'
  grpc: '>=3.2.4'
  logger: ^2.4.0
  statemachine: ^3.3.1
  meta: ^1.16.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
